// Angular/Angular/Day05/day05/src/app/components/products/product-details/product-details.component.ts
import { Component, OnInit } from '@angular/core';
import { ActivatedRoute, RouterLink } from '@angular/router';
import { ProductsService } from '../../services/products.service';

@Component({
  selector: 'app-product-details',
  standalone: true,
  imports: [RouterLink],
  templateUrl: './product-details.component.html',
  styleUrl: './product-details.component.css',
})
export class ProductDetailsComponent implements OnInit {
  productId: any;

  product: any;
  constructor(
    private activatedRoute: ActivatedRoute,
    private productsService: ProductsService
  ) {}
  ngOnInit(): void {
    this.productId = this.activatedRoute.snapshot.params['id'];
    this.product = this.productsService.getProductById(this.productId);
    console.log(this.product);
  }
}

<div class="bg-dark text-light p-5">
  <div class="container">
    <h1 class="text-warning">Product Id : {{ productId }}</h1>
    <p class="lead fs-4 mb-3">Product Name : {{ product.name }}</p>
    <p class="lead fs-4 mb-3">Price: {{ product.price }}</p>
    <p class="lead fs-4 mb-3">quantity:{{ product.quantity }}</p>
    <button [routerLink]="['/products']" class="btn btn-outline-primary">
      Back To Products
    </button>
  </div>
</div>

// React_Group/Day04/final/src/components/ProductDetails.jsx
import React, { useEffect, useState } from 'react'
import { Link, useParams } from 'react-router-dom'

export default function ProductDetails( { products, setProducts } ) {
    let { id } = useParams();

    let [ product, setProduct ] = useState( {} );
    useEffect( () => {
        setProduct( products.find( product => product.id == id ) )
    }, [] )
    return (
        <div className='bg-dark p-5 text-light'>
            <div className="container">
                <h1 className='text-center text-warning mb-4'>Product Details</h1>
                <h3>Product Code : {id}</h3>
                <p className='lead mt-3'>Product Name : {product?.name}</p>
                <p className='lead mt-3'>Product Price :{product?.price}</p>
                <p className='lead mt-3'>Product Quantity : {product?.quantity}</p>
                <p className='lead mt-3'>
                    <i className="text-warning mx-1 bi bi-star-fill"></i>
                    <i className="text-warning mx-1 bi bi-star-fill"></i>
                    <i className="text-warning mx-1 bi bi-star-fill"></i>
                    <i className="text-warning mx-1 bi bi-star-fill"></i>
                    <i className="text-warning mx-1 bi bi-star-fill"></i>
                </p>
                <Link to='/products' className='btn btn-secondary'>Back To Products</Link>
            </div>

        </div>
    )
}
